action_dim: 4
added: true
batch_size: 64
beta1: 0.9
config: configs/training_default_depth_added.yaml
contact: 1.0
continuation: false
cuda: true
dataset: dataset/triangle_real_data/
dataset_params: {action_dim: 4, force_name: force}
depth: 1.0
deterministic: true
dev: false
eedelta: 1.0
encoder: false
ep_length: 50
force: 1.0
img_record_n: 500
latest_weights: logging/202304211423_/models/weights_itr_49.ckpt
load: ''
log_level: INFO
logging_folder: logging/202304211423_
lr: 0.0001
max_epoch: 50
notes: ''
num_workers: 8
opticalflow: 1.0
pairing: 1.0
proprio: 1.0
sceneflow: 1.0
seed: 1234
start_weights: ['']
test: true
training_type: selfsupervised
usingDepth: true
val_ratio: 0.2
vision: 1.0
weighted: false
zdim: 128
